/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Player.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

function Player(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Player.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
      actions.idle.play()
      if(props.action === 'runForward'){
        actions.runForward.play()
      }
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Erika_Archer_Body_Mesh" geometry={nodes.Erika_Archer_Body_Mesh.geometry} material={materials['Akai_MAT.001']} skeleton={nodes.Erika_Archer_Body_Mesh.skeleton} />
          <skinnedMesh name="Erika_Archer_Clothes_Mesh" geometry={nodes.Erika_Archer_Clothes_Mesh.geometry} material={materials['eyelash_MAT.001']} skeleton={nodes.Erika_Archer_Clothes_Mesh.skeleton} />
          <skinnedMesh name="Erika_Archer_Eyelashes_Mesh" geometry={nodes.Erika_Archer_Eyelashes_Mesh.geometry} material={materials['Body_MAT.001']} skeleton={nodes.Erika_Archer_Eyelashes_Mesh.skeleton} />
          <skinnedMesh name="Erika_Archer_Eyes_Mesh" geometry={nodes.Erika_Archer_Eyes_Mesh.geometry} material={materials['EyeSpec_MAT.001']} skeleton={nodes.Erika_Archer_Eyes_Mesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Player.glb')

export default Player;